### ISSUE TITLE
Move this repo under the browserpass org

### ISSUE THREAD

**Issue by max-baz** [browserpass/native.pl#1]
Hey, can I move this repo under the new [browserpass org](https://github.com/browserpass/)? 
I personally use this script a lot, but I'm afraid nobody else knows of its existence.

I can copy or fork the script as well, but I want to preserve your name in the commits 😉 

If you agree, the simplest way is to give me admin rights on this repo and I'll do the rest - your admin rights will obviously remain.

**Comment by chrboe** [comment]
Hey, cool that it's actually useful to someone :smile: 

Of course you can, I'll give you admin rights right away.

**Comment by max-baz** [comment]
Hm, this doesn't allow me accessing the settings - can you instead transfer the repo to me?
